### ISSUE TITLE
Server down

### ISSUE THREAD

**Issue by eeuq7mi** [mudkipme/52poke#24]
Thanks for the website. Here I want to report that the server is down recently.
[ping](http://ping.chinaz.com/wiki.52poke.com)

**Comment by eeuq7mi** [comment]
It seems that Ping sometimes is ok, but browser got `ERR_CONNECTION_RESET`.

Alternatives:
1. [Official Dex](https://cn.portal-pokemon.com/play/pokedex/)
2. [PokeDex](https://www.pokedex.app/zh/home)

**Comment by lucka-me** [comment]
It seems the server works properly for me, except 504 error at 20:00GMT everyday, which is a known issue.

@eeuq7mi Could you please check your network environment including your DNS configuration and ISP status? It might be relevant.

**Comment by eeuq7mi** [comment]
Browser (PC side, use wired network) return either `ERR_TIMED_OUT` or `ERR_CONNECTION_RESET`. Mobile 4G Network doesn't have this problem, but image loding is quite slow when visiting this site.
Perhaps reason is ISP problem in my region.
Thanks for detailed reply.

**Comment by eeuq7mi** [comment]
I tested it again today using wired network. Now the 52poke website is available in my region. Thanks.
